### ISSUE TITLE
pygame.error: Unable to make GL context current

### ISSUE THREAD

**Issue by laolinde** [idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning#23]
Thank you so much for your work.But when I run the code using the instruction python continuous_driver.py --exp-name=ppo --train=False, there is an error as follows.

Traceback (most recent call last):   
File "/home/*****/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning-main/simulation/sensors.py", line 63, in <lambda>   self.sensor.listen(lambda image: CameraSensorEnv._get_third_person_camera(weak_self, image))  File "/home/cec20/LinHuilong/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning-main/simulation/sensors.py", line 87, in _get_third_person_camera pygame.display.flip() 
pygame.error: Unable to make GL context current

I would be very grateful if you can give me some tips!

**Comment by Yandong-Luo** [comment]
pip uninstall pygame
pip install pygame==1.9.6
